# Generated by Django 6.1.1 on 2026-10-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='host_username',
            new_name='host',
        ),
    ]
